module.exports = {
  //ApiAction

  LOGIN_CALL: 'LOGIN_CALL',
  VERIFY_OTP_CALL: 'VERIFY_OTP_CALL',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  GET_PROFILE_CALL: 'GET_PROFILE_CALL',
  GET_ORDERS_CALL: 'GET_ORDERS_CALL',
  GET_STORES_CALL: 'GET_STORES_CALL',
  POST_ORDER_CALL: 'POST_ORDERS_CALL',
  GET_LISTS_CALL: 'GET_LISTS_CALL',
  POST_LIST_CALL: 'POST_LIST_CALL',

  //LoginAction
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",

  ADD_TO_CART: "ADD_TO_CART"
};
